# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='顾客姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_num', models.IntegerField(default=1, verbose_name='就餐人数')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='达到时间')),
                ('time', models.CharField(choices=[('half', '30'), ('one', '60'), ('one_half', '90'), ('two', '120'), ('two_half', '150'), ('three', '180'), ('three_half', '210'), ('four', '240')], default='half', max_length=6, verbose_name='用餐时长')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Customer', verbose_name='顾客')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_size', models.CharField(choices=[('S', '小桌'), ('M', '中桌'), ('L', '大桌')], max_length=2, verbose_name='桌子尺寸')),
                ('seat_num', models.IntegerField(default=0, verbose_name='座位数')),
            ],
        ),
        migrations.CreateModel(
            name='WalkIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='顾客姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('people_num', models.IntegerField(default=1, verbose_name='就餐人数')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='达到时间')),
                ('time', models.CharField(choices=[('half', '30'), ('one', '60'), ('one_half', '90'), ('two', '120'), ('two_half', '150'), ('three', '180'), ('three_half', '210'), ('four', '240')], default='half', max_length=6, verbose_name='用餐时长')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Table', verbose_name='桌号')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Table', verbose_name='桌号'),
        ),
    ]
