# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '顾客', 'verbose_name_plural': '顾客'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '预约', 'verbose_name_plural': '预约'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': '餐桌', 'verbose_name_plural': '餐桌'},
        ),
        migrations.AlterModelOptions(
            name='walkin',
            options={'verbose_name': '就餐', 'verbose_name_plural': '就餐'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('half', '30'), ('one', '60'), ('one_half', '90'), ('two', '120'), ('two_half', '150'), ('three', '180'), ('three_half', '210'), ('four', '240')], default='half', max_length=10, verbose_name='用餐时长'),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='time',
            field=models.CharField(choices=[('half', '30'), ('one', '60'), ('one_half', '90'), ('two', '120'), ('two_half', '150'), ('three', '180'), ('three_half', '210'), ('four', '240')], default='half', max_length=10, verbose_name='用餐时长'),
        ),
    ]
