# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20180530_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='达到时间'),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='达到时间'),
        ),
    ]
