# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20180530_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('half', '30'), ('one', '1:00'), ('one_half', '1:30'), ('two', '2:00'), ('two_half', '2:30'), ('three', '3:00'), ('three_half', '3:30'), ('four', '4:00')], default='half', max_length=10, verbose_name='用餐时长'),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='time',
            field=models.CharField(choices=[('half', '30'), ('one', '1:00'), ('one_half', '1:30'), ('two', '2:00'), ('two_half', '2:30'), ('three', '3:00'), ('three_half', '3:30'), ('four', '4:00')], default='half', max_length=10, verbose_name='用餐时长'),
        ),
    ]
