# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20180530_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.DateField(default=datetime.datetime.now, verbose_name='到达日期'),
        ),
        migrations.AddField(
            model_name='walkin',
            name='day',
            field=models.DateField(default=datetime.datetime.now, verbose_name='到达日期'),
        ),
    ]
