# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20180530_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(choices=[('0', '18:00'), ('1', '18:30'), ('2', '19:00'), ('3', '19:30'), ('4', '20:00'), ('5', '20:30'), ('6', '21:00'), ('7', '21:30'), ('8', '22:00'), ('9', '22:30'), ('10', '23:00'), ('11', '23:30')], max_length=20, verbose_name='达到时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('1', '0.5'), ('2', '1'), ('3', '1.5'), ('4', '2'), ('5', '2.5'), ('6', '3'), ('7', '3.5'), ('8', '4')], default='1', max_length=10, verbose_name='用餐时长'),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='date',
            field=models.CharField(choices=[('0', '18:00'), ('1', '18:30'), ('2', '19:00'), ('3', '19:30'), ('4', '20:00'), ('5', '20:30'), ('6', '21:00'), ('7', '21:30'), ('8', '22:00'), ('9', '22:30'), ('10', '23:00'), ('11', '23:30')], max_length=20, verbose_name='达到时间'),
        ),
        migrations.AlterField(
            model_name='walkin',
            name='time',
            field=models.CharField(choices=[('1', '0.5'), ('2', '1'), ('3', '1.5'), ('4', '2'), ('5', '2.5'), ('6', '3'), ('7', '3.5'), ('8', '4')], default='1', max_length=10, verbose_name='用餐时长'),
        ),
    ]
